#!/usr/bin/env python

import sys

from rqt_micro_epsilon_scancontrol.gui import ScanControlGui
from rqt_gui.main import Main

plugin = 'rqt_micro_epsilon_scancontrol'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))